#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
source $HOME/.bash_aliases

# escape bindings i have become too used to
bindkey jk vi-cmd-mode
bindkey kj vi-cmd-mode

# aliases from oh-my-zsh
source $HOME/.Git-zsh/oh-my-zsh/plugins/archlinux/archlinux.plugin.zsh
