#!/usr/bin/env sh

# remove the old one
[ -e "xuse" ] && rm xuse

# copy target
cat "$1" > xuse

# sed change stuff to add transparency
sed -e "s/define /define a/g; s/ #/ #D9/g;" $1 >> xuse

# reload Xresources
xrdb $HOME/.Xresources

export barBG=$(xrdb -query | grep "*background" | awk '{print $NF}')
export barFG=$(xrdb -query | grep "*foreground" | awk '{print $NF}')

# chang bsp stuff
pgrep bspwm && {

  bspc config normal_border_color "${barBG}"
  bspc config focused_border_color "${barFG}"
  bspc config active_border_color "${barFG}"

  bargaps.sh && bargaps.sh 2> /dev/null

}

# reset wall
hsetroot -solid "${barBG}"
