#!/bin/bash

# Functions for all
getwifiname() {
	Tico=" "
	# wifi essid
	T=$(iwconfig "wlp8s0" | grep -i essid \
		| awk '{print $NF}' | \
		sed -e  "s/://g; s/ESSID//g; s/\"//g")
	# output to stdin
	echo "${Tico}${T} "
}
getdatevalue() {
	# date value
	echo "X1$(date) << DATE"
}
getbatteryinfo() {
	BAT="/sys/class/power_supply/BAT0"
	capacity=$(cat "${BAT}/capacity")
	status=$(cat "${BAT}/status")
	# spit out info
	echo "X1${capacity} ${status} << BAT"
}
getvolumeinfo() {
	aout=$(amixer --quiet sget Master)
	state=$(echo $aout | grep -P 'Front Right:' | grep -Po 'off')
	perc=$(echo $aout | grep -P 'Front Right:' | grep -Po '\d{2,3}\%')
	if [ -n "$state" ]
	then
		 echo ""
	else
		 echo " $perc"
	fi
}
getworkspaces() {
	blackmagic() {
		# do some things
		case $1 in
			[ou]*)
				X=$(echo -e "$1" | sed -e "s/[ou]//g")
					echo -e "$Y($X)$Y"
				;;
			[OU]*)
				X=$(echo -e "$1" | sed -e "s/[OU]//g")
					echo -e "$Y[$X]$Y"
				;;
			f*)
				X=$(echo -e "$1" | sed -e "s/f//g")
					echo -e "$Y$X$Y"
				;;
			F*)
				X=$(echo -e "$1" | sed -e "s/F//g")
					echo -e "$Y$X$Y"
				;;
			[WwMm]*)
				;;
		esac
	}

	# the goods
	bspstat=$(bspc wm -g | sed -e "s/:/ /g")
	# the text
	Y=" "
	yabarstat=""
	# the trips
	for ID in $bspstat; do
		yabarstat="$yabarstat$(blackmagic $ID)"
	done
	echo "$yabarstat"
}
