#! /bin/sh
source ~/.bash_aliases
# HDMI1 output settings:
# Screen Padding
bspc config top_padding         4
bspc config left_padding        4
bspc config right_padding       4
bspc config bottom_padding      4
# Gaps and such:
bspc config border_width    2
bspc config window_gap		8
bspc config split_ratio         0.50
bspc config borderless_monocle  false
bspc config gapless_monocle     false
#bspc config focus_by_distance   true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
# output colours:
BG=$(xrdb -query | grep " *background" | awk '{print $NF}')
FG=$(xrdb -query | grep " *foreground" | awk '{print $NF}')
bspc config normal_border_color $BG
bspc config focused_border_color $FG
bspc config active_border_color $FG
# monitors
bspc monitor eDP1 -d 'I' 'II' 'III' 'IV' 'V'
# set up second monitor if connected
( xrandr --query | grep "HDMI1 d" ) 1> /dev/null || {
	xrandr --output HDMI1 --auto --below eDP1
	bspc monitor HDMI1 -d 'I' 'II' 'III' 'IV' 'V'
}
# some rules:
bspc rule -a Gimp desktop="^3" state=floating follow=on
bspc rule -a qutebrowser desktop="^2" follow=on
#sh $HOME/.fehbg
#bspc config external_rules_command "$(which external_rules.sh)"
setblurredwall $(tail -n 1 .fehbg | awk '{print $NF}' | sed -e "s/'//g") 20
lemtoggle.sh start
