#! /bin/sh
[ -e $HOME/.local/bspwm.log ] && rm $HOME/.local/bspwm.log 
{
	source ~/.bash_aliases
	# Gaps and such:
	bspc config border_width	 2
	bspc config window_gap		8
	bspc config split_ratio			0.50
	bspc config borderless_monocle  true
	bspc config gapless_monocle	  false
	bspc config borderless_monacle true
	bspc config focus_follows_pointer true
	bspc config pointer_follows_focus true
	bspc config pointer_follows_monitor true
	# output colours:
	bspc config normal_border_color $barBG
	bspc config focused_border_color $barFG
	bspc config active_border_color $barFG
	bspc config presel_feedback_color $barFG
	# monitors {
	bspc monitor eDP1 -d 'I' 'II' 'III' 'IV' 'V'
	#}
	# some rules:{
		#Gimp{ single window mode so i can tile
		#bspc rule -a "Gimp" desktop="^4"
		#bspc config -d "^4" pointer_follows_focus false
		#}
		bspc rule -a "qutebrowser" desktop="^2" follow=on
		bspc rule -a "Firefox" desktop="^2" follow=on
		bspc rule -a "Zathura" state=tiled follow=on
		bspc rule -a "URxvtQuake" state=floating sticky=on
		bspc rule -a "URxvtRun" state=floating sticky=on
		bspc rule -a "Butter" desktop="^1" follow=on
	#}
	# bar & rectify padding
	squeezewin.sh 30
} 2> $HOME/.local/bspwm.log 
